#!/bin/sh

# get temperature
therm_status="$(acpi -t | awk -F '[[:space:]]+|,' '{ print $5 }' |cut -d'.' -f1)"

# get cpu
read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))
cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

# create output
printf "[ 💽%2s%% 🌡%s°C ]\\n" $cpu $therm_status
