#!/bin/sh

weatherreport="${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
rain=$(printf "%s" "$(sed '16q;d' $weatherreport | grep -wo "[0-9]*%" | sort -rn | sed "1q" | tr -d '\n')")
temp=$( printf "%s" "$(sed '13q;d' $weatherreport | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print "❄" $1 "°","☀" $2 "°"}')")

iconrain="☂"

printf "[ %s%s %s ]" $iconrain $rain "$temp"
