#!/bin/sh

# get diskspace
rootfree=$(df -h | awk '$6=="/"{print $4}')
homefree=$(df -h | awk '$6=="/home"{print $4}')

# create output
echo  "[ 💾${rootfree} 🏠${homefree} ]"
# echo  "[ 💾${rootfree} ]"
# echo  "[ 🏠${homefree} ]"
