#!/bin/sh

read -r actual_brightness </sys/class/backlight/intel_backlight/actual_brightness
read -r max_brightness </sys/class/backlight/intel_backlight/max_brightness
backlight="$((actual_brightness*100/max_brightness))"
icon="☀"
icon2="💡"

printf "[ %s%3s%% ]" ${icon2} $backlight
