#!/bin/sh

# what modules to display
# MODULES="mpd pomodoro hides apt mounts volume disk ram cpu battery internet date"
MODULES="calcurse mpd pomodoro hides apt rss mounts volume disk ram cpu battery nettraf internet iplocate kbselect date"

# update intervall
INTERVALL="1.0"
